### ISSUE TITLE
Reviews-Full-Stack Question on stretch tasks - One to Many on tags, or many to many.

### ISSUE THREAD

**Issue by Dean110** [WeCanCodeIT/java-exercises#3]
Reviews-Full-Stack Question
In the project overview/assignment I have the following question:
Should this be a many to many relationship instead of a one to many relationship?
> Update Review so that it can have tags associated with it. (One review, many tags.)

Seems it would be more useful and real world like for it to be many to many.

**Comment by donhamiltoniii** [comment]
Many-to-many is the right choice here as multiple reviews can have the same tags and the same tags can be applied to multiple reviews.

**Comment by btforsythe** [comment]
Thanks for the catch, @Dean110. I updated the description.
